apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: onlock-front
  name: onlock-front
  namespace: onlock-test
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 5
  selector:
    matchLabels:
      app: onlock-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: onlock-front
    spec:
      containers:
      - image: DOCKER_APPLICATION_IMAGE #CHANGE
        imagePullPolicy: IfNotPresent
        name: onlock-front
      restartPolicy: Always
      terminationGracePeriodSeconds: 5